# fly.toml app configuration file generated for meme-api on 2023-12-31T15:58:41+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meme-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
[env]
  APP_URL_ENV = "example.com"
