# Exported from Render on 2025-01-21T19:42:07Z
services:
- type: web
  name: meme-api
  runtime: docker
  repo: https://github.com/madhuryadutta/meme-api
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: APP_URL_ENV
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
  domains:
  - meme-api.databytedigital.com
  previews:
    generation: automatic
version: "1"
